### ISSUE TITLE
Trip headings duplicate of trip ID

### ISSUE THREAD

**Issue by markerpen** [planarnetwork/transxchange2gtfs#8]
Great work so far!

One thing I've noticed is that trip_headsign and trip_short_name in trips.txt are duplicates of the auto-generated trip_id.

trip_short_name should be the name on the destination screen on the front of the bus (e.g. 'Dagenham Tesco') and trip_headsign should be blank unless the bus' destination screen changes mid-journey (quite rare, and I haven't seen it in the TNDS yet).

You can get the trip_short_name in one of two places:

Service > StandardService > Destination
or
Service > StandardService > JourneyPattern > DestinationDisplay

depending on the region and operator supplying the raw data to Traveline.

The direction_id in trips.txt is always set to 0 (outbound) it seems - you can find the direction of each journey in Service > StandardService > JourneyPattern > Direction.

Hope this helps!

**Comment by linusnorton** [comment]
Thanks for the suggestions.

I have set the trip short name to `Service > StandardService > Destination` but not catered for ` Service > StandardService > JourneyPattern > DestinationDisplay` (mostly due to lack of examples in my data set). 

I have also set the direction according to `Service > StandardService > JourneyPattern > Direction`. 

I've published 1.1.0 which should contain the new behaviour. Would you mind checking that the outcome is what you expect?
